version: '3.8'

services:
  db:
    image: postgres:16
    container_name: fullstack_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fullstack_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT__Key=ThisIsMySuperSecureAndLongKeyForDotNet9AuthApp2024
      - JWT__Issuer=FullstackIssuer
      - JWT__Audience=FullstackAudience
    ports:
      - "5207:8080"
    depends_on:
      - db
    networks:
      - fullstack_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fullstack_frontend
    environment:
      - API_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fullstack_network

volumes:
  postgres_data:

networks:
  fullstack_network:
    driver: bridge