services:
  db:
    image: postgres:latest
    container_name: dbtestpg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}"
      JWT__KEY: ${JWT__KEY}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:8080"
    container_name: frontend
    restart: always
    environment:
      VITE_API_URL: "http://backend:8080"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge