name: Deploy Fullstack App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          docker build -t axel555/the-debuegies_fullstack-backend:latest ./backend
          docker build -t axel555/the-debuegies_fullstack-frontend:latest ./frontend

      - name: Push to DockerHub
        run: |
          docker login -u axel555 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push axel555/the-debuegies_fullstack-backend:latest
          docker push axel555/the-debuegies_fullstack-frontend:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

    